### ISSUE TITLE
咨询一下项目demo的开发环境

### ISSUE THREAD

**Issue by jacksonsc007** [NVIDIA/trt-samples-for-hackathon-cn#68]
大家好，我在运行04-parser/pytorch-Onnx-tensorrt时，生成的Onnx模型无法序列化成EngineString，想咨询一下大家的开发环境。
本人环境如下：
Windows 10; 
pytorch 1.9.0
tensorrt 8.5.1.7
onnx 1.31.1

报错内容如下：
`Succeeded converting model into ONNX!
[03/16/2023-09:47:51] [TRT] [I] [MemUsageChange] Init CUDA: CPU +261, GPU +0, now: CPU 10138, GPU 1787 (MiB)
[03/16/2023-09:47:52] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +237, GPU +72, now: CPU 10494, GPU 1859 (MiB)
Succeeded finding ONNX file!
[03/16/2023-09:47:53] [TRT] [W] onnx2trt_utils.cpp:377: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[03/16/2023-09:47:53] [TRT] [W] Tensor DataType is determined at build time for tensors not marked as input or output.
Succeeded parsing .onnx file!
x <tensorrt.tensorrt.ITensor object at 0x000001DE21842E70>
tensor.name = y
tensor.shape = (-1, 10)
[03/16/2023-09:47:53] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 10426, GPU 1867 (MiB)
[03/16/2023-09:47:53] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +106, GPU +48, now: CPU 10532, GPU 1915 (MiB)
[03/16/2023-09:47:53] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[03/16/2023-09:48:00] [TRT] [E] 2: [ltWrapper.cpp::nvinfer1::rt::CublasLtWrapper::setupHeuristic::349] Error Code 2: Internal Error (Assertion cublasStatus == CUBLAS_STATUS_SUCCESS failed. )
[03/16/2023-09:48:00] [TRT] [E] 2: [builder.cpp::nvinfer1::builder::Builder::buildSerializedNetwork::751] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
Failed building engine!`

**Comment by jacksonsc007** [comment]
@wili-65535

**Comment by wili-65535** [comment]
Sorry we did not test the examples in Windows.
In addition, we recommend to use NVIDIA-optimized docker (https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html) to run the examples.

**Comment by jacksonsc007** [comment]
Thanks for the reply. It turned out that the examples do have some issues in Windows and now I fall back to the linux dev environment.
